spring.application.name=hasta
spring.datasource.url=jdbc:mysql://localhost:3306/hasta
spring.datasource.username=hasta
spring.datasource.password=hasta
spring.jpa.hibernate.ddl-auto=update

keycloak.server-url=http://localhost:8180
keycloak.realm=hasta-realm
keycloak.admin-username=admin
keycloak.admin-password=admin

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/hasta-realm

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

#server.ssl.key-store-password=hasta
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=/home/Fra/IdeaProjects/hasta/certificate.p12