export enum Category {
  CANCELLERIA = 'CANCELLERIA',
  ARREDAMENTI = 'ARREDAMENTI',
  VESTITI = 'VESTITI',
  ACCESSORI = 'ACCESSORI',
  ELETTRONICA = 'ELETTRONICA',
  COLLEZIONISMO = 'COLLEZIONISMO',
  GIOCHI_E_GIOCATTOLI = 'GIOCHI_E_GIOCATTOLI',
  SPORT_E_TEMPO_LIBERO = 'SPORT_E_TEMPO_LIBERO',
  AUTO_E_MOTO = 'AUTO_E_MOTO',
  ELETTRODOMESTICI = 'ELETTRODOMESTICI',
  LIBRI_E_MEDIA = 'LIBRI_E_MEDIA',
  SALUTE_E_BENESSERE = 'SALUTE_E_BENESSERE',
  ALTRO = 'ALTRO',
}

export interface CategoryInfo {
  id: Category;
  label: string;
  icon: string;
}
